### ISSUE TITLE
Missing comma in component initializer with more than one parameter

### ISSUE THREAD

**Issue by mikeyclarke** [shackley/swift-blade#3]
Hey there!

I’m having an issue where components with an initializer containing more than one parameter are being expanded without a separating comma.

![Screenshot 2024-01-26 at 18 12 22](https://github.com/shackley/swift-blade/assets/2198581/873f8d12-6b20-405c-a284-97ffaff455f9)

I don’t _think_ I’m doing anything stupid. Kinda wonder if it’s a bug in the swift-syntax package? I’m not very well aquatinted with Swift Macros yet but I had a quick look over there and I did spot [this issue](https://github.com/apple/swift-syntax/issues/1937) which may be related?

**Comment by shackley** [comment]
Hi @mikeyclarke,

Thanks for the report!

This was actually bug in the `@Component` macro expansion logic! It has been fixed in this commit https://github.com/shackley/swift-blade/commit/71c9bb45537074063c4e1fc3a7d2fb0a3fa45f41.

The fix has been included in the [0.1.4](https://github.com/shackley/swift-blade/releases/tag/0.1.4) release.

**Comment by mikeyclarke** [comment]
Awesome, thank you! 🙏
